### ISSUE TITLE
Chefs not making villager food when cooking

### ISSUE THREAD

**Issue by nelarth** [TangoTek/TekTopia-Community#549]
**Describe the bug
When the chef cooks potatoes, it doesn't wait for the whole batch of potatoes to cook and pulls out 2-3 of them while the rest are cooking, these come out with green names. The next time he comes back to grab the rest of the potatoes, they are picked up as normal white name baked potatoes

** Server/Location **
I am playing on the main 1 survival server at 1112, -8076

**Comment by ravenclawnc12** [comment]
none of my potatoes or meat is being cooked correctly.

**Comment by ravenclawnc12** [comment]
same with blacksmith smelting

**Comment by Darelk0** [comment]
> 
> 
> **Describe the bug
> When the chef cooks potatoes, it doesn't wait for the whole batch of potatoes to cook and pulls out 2-3 of them while the rest are cooking, these come out with green names. The next time he comes back to grab the rest of the potatoes, they are picked up as normal white name baked potatoes
> 
> ** Server/Location **
> I am playing on the main 1 survival server at 1112, -8076

This is happening to me also

Minecraft survival 2 Darloc Village
3461 -8685

![2019-06-29_00 06 43](https://user-images.githubusercontent.com/51474789/60379940-256ca500-9a02-11e9-835f-5156df76e2d8.png)
![2019-06-29_00 07 07](https://user-images.githubusercontent.com/51474789/60379941-256ca500-9a02-11e9-8ae9-8cd7e831e9f2.png)
![2019-06-29_00 07 15](https://user-images.githubusercontent.com/51474789/60379942-256ca500-9a02-11e9-86ac-d38f996e7251.png)

**Comment by MommaBear1081** [comment]
I am having this with both my chefs and blacksmiths. I think it is when they use oak to make charcoal. I am finding vanilla charcoal in their inventories. I have not provided anything for my villagers and cleared out all vanilla items, weeks ago.

**Comment by SaltyJohnson94** [comment]
still having this is 1.0.51. I witnessed a villager put villager oak into the furnace as fuel and a villager potato in to cook and out came a normal non villager potato.

**Comment by TangoTek** [comment]
Fixed in 1.0.51

**Comment by MorsDux** [comment]
this bug is still around. villager coal + villager potatoe -> non-villager baked potatoe (or at least some.)
